---
title: "critical appraisal report"
format: asciidoc
date: "`r Sys.Date()`"
params: 
  n : NA
---

```{r include=FALSE}
options(tinytex.verbose = TRUE)

```

**Please note** that raRoB-vet is currently under development and this is a draft version.

*This report is produced by raRoB-vet tool. This tool is Funded by the European Union. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or the European Food Safety Authority (EFSA). Neither the European Union nor EFSA can be held responsible for them.*



**Author of the assessment:** `r params$n[1]`

**Study Title:** `r params$n[2]`

**Study Abstract:**

`r params$n[3]`

The has been pre-registered: `r params$n[4]`

**Author's note:** 

`r params$n[5]`

**Study design:** `r params$n[6]`

**Appropriateness of the selected study design for the research question** `r params$n[7]`

**Primary versus secondary data:**

`r params$n[8]`

## Selection

**Eligibility criteria:** `r params$n[9]`

Notes:   
`r params$n[10]`

**Comparability of groups:** `r params$n[11]`

Notes:  
`r params$n[12]`

**Failure rate (non-response rate):** `r params$n[13]`

Notes:  
`r params$n[14]`

**Time frames:** `r params$n[15]`

Notes:  
`r params$n[16]`

## Exposure

**Methodology of exposure measurements:** `r params$n[17]`

Notes:  
`r params$n[18]`

## Outcome

**Methodology of outcome measurements:** `r params$n[19]`

Notes:  
`r params$n[20]`

## Confounding

**Accounting for confounding:** `r params$n[21]`

Notes:  
`r params$n[22]`

**Confounding assessments:** `r params$n[23]`

Notes:  
`r params$n[24]`

## Censoring

**Adequacy of length of observation periods:** `r params$n[25]`

Notes:  
`r params$n[26]`

**Amount and handling of dropouts:** `r params$n[27]`

Notes:  
`r params$n[28]`

## Analysis

**Statistical methods:** `r params$n[29]`

Notes:  
`r params$n[30]`

**Handling of missing values:** `r params$n[31]`

Notes:  
`r params$n[32]`

## Selective reporting

**Selective reporting of outcomes:** `r params$n[33]`

Notes: `r params$n[34]`